### ISSUE TITLE
Use lastVisit cookie + javascript for unread instead of server-side logic

### ISSUE THREAD

**Issue by SjonHortensius** [mnapoli/externals#10]
Thanks for this very useful interface to internals. Would you consider replacing the current GH login-requirement for a simple cookie that compares lastVisit to a lastMessage property of each thread?

**Comment by mnapoli** [comment]
Hi, currently I record every message read by each user: that allows to have a granular record of what you have read and what you haven't. It could be exploited more usefully on the website (e.g. record reading a mail only if you actually read it (display on screen). At first I considered using localstorage/cookies but the problem is that it won't work if you use multiple devices (e.g. home/work/mobile).

Anyway a first step would be to store which *threads* have been read using cookies, that would at least improve the life for some users. But feel free to send a pull request.
