### ISSUE TITLE
Weird behaviour on one particular mail

### ISSUE THREAD

**Issue by francislavoie** [mnapoli/externals#146]
https://externals.io/message/111312#111628

It was rendered as `...` but clicking `View Source` revealed that there was in fact a mail sent.

I don't know enough to understand why this wasn't parsed correctly but I figured I'd mention it just in case.

**Comment by mnapoli** [comment]
Here is the content of the email:

```
> With the choice being @@ or @{} - nothing would stop someone (not me ;-)=
)
> to make an RFC for 8.1 or later proposing to add a second syntax.
Sure. If @@ would end up winning again (who knows at this point), at
least one positive thing is that @{} could be added later without having
a BC break, which reduces the potential future benefits of an enclosed
syntax, as it is still possible if needed.
```

It is then rendered as Markdown. Let's have a look using GitHub's markdown rendering:

> With the choice being @@ or @{} - nothing would stop someone (not me ;-)=
)
> to make an RFC for 8.1 or later proposing to add a second syntax.
Sure. If @@ would end up winning again (who knows at this point), at
least one positive thing is that @{} could be added later without having
a BC break, which reduces the potential future benefits of an enclosed
syntax, as it is still possible if needed.

As we can see, the author started typing _in_ the quote, which makes a big blockquote. And on externals.io we collapse (i.e. replace with `...`) the last quote, because usually it's the email we are replying to.

In the end, I'm not sure there is much we can do here :/

**Comment by staabm** [comment]
Maybe add something which allows to expand the text when pressing on "..."?

**Comment by mnapoli** [comment]
@staabm yes good point! I'll keep the issue open.

**Comment by gharlan** [comment]
There is already an issue for this: #50

**Comment by mnapoli** [comment]
👍  thanks
