### ISSUE TITLE
Missing messages in thread

### ISSUE THREAD

**Issue by pbowyer** [mnapoli/externals#187]
In the following messages appear in the Algolia search results but not in the web rendition of the thread:

https://externals.io/email/119907/source
https://externals.io/email/119950/source

Thread: https://externals.io/message/119834

**Comment by mnapoli** [comment]
Hey just posting a quick update here: I tried to look for these but I cannot explain why they were not imported…

If we have more of these let me know

**Comment by SakiTakamachi** [comment]
Hi. I also ran into this problem recently.

In my case, I know the steps to reproduce. If I first post on a Mac and then post from my iPhone, the thread will no longer be updated.

Regards.

**Comment by SakiTakamachi** [comment]
I understand the cause. It's an iPhone bug.
(There may be similar bugs other than iPhone, but I haven't investigated anything other than iPhone.)

https://discussions.apple.com/thread/250746702

The root email of the thread is not included in the email header reference, so I don't know which thread the email belongs to.

I think the events @pbowyer  reported are probably caused by the same thing.

**Comment by mnapoli** [comment]
Awesome, thanks @SakiTakamachi
