### ISSUE TITLE
Missing thread

### ISSUE THREAD

**Issue by mappu** [mnapoli/externals#58]
Hi,

This entire thread is missing: https://externals.io/message/101193 

It contains some important context that is relevant to this thread: https://externals.io/message/101180

You can see individual messages on http://news.php.net/php.internals that are totally missing on https://externals.io/

Why is it missing?

**Comment by mnapoli** [comment]
I think the root of the issue is that the email we are trying to read (http://news.php.net/php.internals/101178) is referencing another email that is not in php.internals, it is in another mailing list (php.cvs). So the root thread doesn't exist at all in our database…

I was not expecting that at all to be honest, I thought each mailing list was completely separate. But again it's all not clear to me, maybe one could reference emails from anywhere and forward/answer to them with the internals mailing list and that would be the same issue.

**Comment by mnapoli** [comment]
Platform is deploying, this should be fixed.

There will still be no thread root (so it won't appear in the thread list, the thread does not have a unique URL) but at least it can be read now.

Thanks, let me know if that's all good for you.
