### ISSUE TITLE
.at tld in sender gets translated to @ sign

### ISSUE THREAD

**Issue by anbuc** [mnapoli/externals#64]
Noticed [here](https://externals.io/message/102029#102029)

When the sender is `name@example.at (Name)` the sender in externals reads `name@example@Name` instead of only `Name` like it with other tlds

**Comment by mnapoli** [comment]
Oh nice catch, I think it may be because of https://github.com/mnapoli/externals/blob/master/src/Email/EmailAddressParser.php#L46 ?

I guess we could remove that specific behavior if it's not useful here. I imported the class from another open source project so it's possible this is not really useful for us.
