### ISSUE TITLE
Missing button to jump to next unread message

### ISSUE THREAD

**Issue by theodorejb** [mnapoli/externals#97]
I don't see the button anymore when opening a thread with unread messages. It's annoying to have to manually scroll through a long list of messages to find the ones I haven't read yet.

**Comment by mnapoli** [comment]
Yes good catch! I think this commit 13f8548a8b38b1f2028b18d7eecf0e0477c2c597 is not deployed on platform.sh… Weird! And since I still can't access the project on their dashboard (it's broken) I can't understand what's going on…

I'm afraid we are getting closer to the point where we need to move away from there, we have just too many problems unfortunately.

**Comment by mnapoli** [comment]
I have just tried purging all the cache on cloudflare, who knows maybe that's it. But since it's Javascript in HTML (not an external file) I highly doubt it.

**Comment by mnapoli** [comment]
@staabm according to Platform's support it should be good now, they fixed "a lock" and master should be deployed. But I still don't see the button 🤔 	Can you spot if you see your latest changes deployed?

I'll try to push a dummy commit to see if it redeploys

**Comment by staabm** [comment]
since I can see the dns-prefetch markup, it seems it was deployed

![grafik](https://user-images.githubusercontent.com/120441/47722736-6209b600-dc53-11e8-8dcd-b1f82c49a739.png)

**Comment by staabm** [comment]
I can see some js error related to jquery removal. will have a deeper look.

**Comment by staabm** [comment]
btw: @mnapoli did you intenionally remove the the staging deployment integration with platform.sh ?

**Comment by mnapoli** [comment]
nope it should still work supposedly 😒
